version: '3.8'

services:

  db:
    image: postgres:15.4
    pull_policy: never
    container_name: home.db
    restart: always
    environment:
      POSTGRES_DB: {{ POSTGRES_DB }}
      POSTGRES_USER: {{ POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
      TZ: "Asia/Yekaterinburg"
      PGTZ:  "Asia/Yekaterinburg"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d home"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  config-server:
    image: "maxgladikov/home.config_server:latest"
    pull_policy: always
    container_name: home.config_server
    healthcheck:
     test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
     interval: 2s
     timeout: 3s
     retries: 2
     start_period: 40s
    ports:
      - '8888:8888'
    networks:
      - backend

  discovery-service:
    image: "maxgladikov/home.discovery_service:latest"
    pull_policy: always
    container_name: home.discovery_service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    healthcheck:
     test: "curl --fail --silent localhost:8000/actuator/health/readiness | grep UP || exit 1"
     interval: 2s
     timeout: 3s
     retries: 2
     start_period: 20s
    ports:
      - '8000:8000'
    networks:
      - backend
    depends_on:
      config-server:
        condition: service_healthy

  gateway-service:
    image: "maxgladikov/home.gateway_service:latest"
    pull_policy: always
    container_name: home.gateway_service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    healthcheck:
     test: "curl --fail --silent localhost:9002/actuator/health/readiness | grep UP || exit 1"
     interval: 2s
     timeout: 3s
     retries: 2
     start_period: 20s
    ports:
      - '9002:9002'
    networks:
      - backend
    depends_on:
      discovery-service:
        condition: service_healthy

  telegram_bot:
    image: "maxgladikov/home.telegram_bot:latest"
    pull_policy: always
    container_name: home.telegram_bot
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      BOT_NAME: {{ BOT_NAME }}
      BOT_TOKEN: {{ BOT_TOKEN }}
    healthcheck:
      test: "curl --fail --silent localhost:9001/actuator/health/readiness | grep UP || exit 1"
      interval: 1m
      timeout: 3s
      retries: 2
      start_period: 30s
    networks:
      - backend
    ports:
      - '9001:9001'
    depends_on:
      gateway-service:
        condition: service_healthy


  climate_service_online:
    image: "maxgladikov/home.climate_service_online:latest"
    pull_policy: always
    container_name: home.climate_service_online
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 1m
      timeout: 3s
      retries: 2
      start_period: 30s
    networks:
      - backend
      - frontend
    ports:
      - '9000:9000'
    environment:
      SPRING_PROFILES_ACTIVE: {{{ROFILE}}
    depends_on:
      gateway-service:
        condition: service_healthy

  frontend:
    image: "maxgladikov/home.frontend:1.0.2"
    pull_policy: always
    container_name: home.frontend
    networks:
      - frontend
    ports:
      - '80:80'
    depends_on:
      climate_service_online:
        condition: service_healthy

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge



