spring:
  application:
    name: climate_service_online

server:
    port: 9000

logging:
  level:
    root: INFO
    org.springframework.web : INFO


custom:
  sensors:
    kitchen : '192.168.0.202'
    bedroom : '192.168.0.203'
    master_bedroom : '192.168.0.204'
    basement : '192.168.0.205'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
