
spring:
  application:
      name: climate_service
  jpa:
    #generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    ddl-auto: none
    show-sql : true

  datasource:
    platform: postgres
  flyway:
    baseline-on-migrate: true
