spring:
  datasource:
    username: db_user
    password: '{cipher}640dab1fd998617e4088578130463b6eea82f0db8a8be81328a819916b8cfde2'
    url: jdbc:postgresql://home.db:5432/home
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
      enabled-by-default: true
