sensors:
  url[0] : '192.168.201.11'
  url[1] : '192.168.201.12'
  url[2] : '192.168.201.13'
  url[3] : '192.168.201.14'
  url[4] : '192.168.201.15'



spring:
  datasource:
    username: "db_user"
    password: {cipher}3caa935ea89c39833d9f1f4e4f1c044a5cc496eeccc18da51362d7adc82a9f14
    url: jdbc:postgresql://localhost:5432/home
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
      enabled-by-default: true
