sensors:
  url[0] : '192.168.201.11'
  url[1] : '192.168.201.12'
  url[2] : '192.168.201.13'
  url[3] : '192.168.201.14'
  url[4] : '192.168.201.15'



spring:
  datasource:
    username: db_user
    password: '{cipher}cb66e4488ebafe0436ae92833fe140e71be59a7aa386b098e7fb42d3e7bb6dab'
    url: jdbc:postgresql://localhost:5432/home
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
      enabled-by-default: true
