
spring:
  application:
      name: climate_service
  jpa:
    #generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    ddl-auto: none
    show-sql : true

  datasource:
    platform: postgres
  flyway:
    baseline-on-migrate: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://discovery-service:8000/eureka/
      defaultZone: http://localhost:8000/eureka/
