
logging:
  level:
    root: INFO
    org.springframework.web : INFO


custom:
  sensors:
    master_bedroom: '192.168.201.11'
    livingroom: '192.168.201.12'
    bedroom: '192.168.201.13'
    kitchen: '192.168.201.14'
    bathroom: '192.168.201.15'

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8000/eureka/




