spring:
  application:
    name: telegram-bot

server:
  port: 9001


logging:
  level:
    root: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - mappings
          - metrics
          - loggers
          - shutdown
          - pause
          - resume
  endpoint:
    health:
      probes:
        enabled: true
