spring:
  application:
    name: telegram-bot
  #main:
   # web-application-type: none
server:
  port: 9001


logging:
  level:
    root: INFO





management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
