spring:
  application:
    name: telegram-bot
  #main:
   # web-application-type: none
server:
  port: 9001


logging:
  level:
    root: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://discovery-service:8000/eureka/
      defaultZone: http://localhost:8000/eureka/




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
