
server:
  port: 8888
#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud: 'INFO'
        
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/maxgladikov/home.git
#          cloneOnStart: true
          searchPaths: configs
          default-label: main
#          skipSslValidation: true
#          refreshRate: 30
#          defaultLabel: main

#encrypt:
# key: 
 
 
 
 