
server:
  port: 8888
#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: 'WARN'
#    org.springframework.cloud: 'INFO'
        
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/maxgladikov/home.git
          cloneOnStart: true
          tryMasterBranch: false
          searchPaths: configs
          default-label: main
          refreshRate: 30

 
 
 